# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:00:32 2018 from module list in Acme::CPANLists::Import::NEILB::Constants version 0.04.

package Acme::CPANModules::Import::NEILB::Constants;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/constants.html]. For the full article, visit the URL.",
  entries     => [
                   { module => "Attribute::Constant" },
                   { module => "Config::Constants" },
                   { module => "Const::Fast" },
                   { module => "Constant::FromGlobal" },
                   { module => "Constant::Generate" },
                   { module => "Devel::Constants" },
                   { module => "Lexical::Import" },
                   { module => "Lexical::Var" },
                   { module => "Scalar::Constant" },
                   { module => "Scalar::Construct" },
                   { module => "Scalar::Readonly" },
                   { module => "constant" },
                   { module => "constant::def" },
                   { module => "constant::defer" },
                   { module => "constant::lexical" },
                   { module => "constant::our" },
                   { module => "ex::constant::vars" },
                 ],
  summary     => "Defining constants (2012)",
};

1;
# ABSTRACT: Defining constants (2012)

