# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:00:32 2018 from module list in Acme::CPANLists::Import::NEILB::HTTPRequesters version 0.04.

package Acme::CPANModules::Import::NEILB::HTTPRequesters;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/http-requesters.html]. For the full article, visit the URL.",
  entries     => [
                   { module => "Furl" },
                   { module => "HTTP::Client" },
                   { module => "HTTP::Lite" },
                   { module => "HTTP::Soup" },
                   { module => "HTTP::Tiny" },
                   { module => "LWP" },
                   { module => "LWP::Curl" },
                   { module => "LWP::Simple" },
                   { module => "Mojo::UserAgent" },
                   { module => "Net::Curl" },
                   { module => "Net::Curl::Simple" },
                   { module => "Net::HTTP" },
                   { module => "Net::HTTP::Tiny" },
                   { module => "URI::Fetch" },
                   { module => "URL::Grab" },
                   { module => "WWW::Curl" },
                   { module => "WWW::Curl::Simple" },
                   { module => "Web::Magic" },
                 ],
  summary     => "Making HTTP requests (2012)",
};

1;
# ABSTRACT: Making HTTP requests (2012)

