# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:00:32 2018 from module list in Acme::CPANLists::Import::NEILB::IPLocation version 0.04.

package Acme::CPANModules::Import::NEILB::IPLocation;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/ip-location.html]. For the full article, visit the URL.",
  entries     => [
                   { module => "Geo::Coder::HostIP" },
                   { module => "Geo::IP" },
                   { module => "Geo::IP2Location" },
                   { module => "Geo::IP::RU::IpGeoBase" },
                   { module => "Geo::IPfree" },
                   { module => "IP::Country" },
                   { module => "IP::Country::DB_File" },
                   { module => "IP::Country::DNSBL" },
                   { module => "IP::Info" },
                   { module => "IP::Location" },
                   { module => "IP::QQWry" },
                   { module => "IP::World" },
                 ],
  summary     => "Locating an IP address (2012)",
};

1;
# ABSTRACT: Locating an IP address (2012)

