# This file was first automatically generated by gen-acme-cpanmodules-module-from-webpage on Wed May 19 09:28:03 2021 from webpage at https://phoenixtrap.com/2021/05/18/a-list-of-perl-list-processing-modules/ by gen-acme-cpanmodules-module-from-webpage (App::CPANModulesUtils version dev).

package Acme::CPANModules::Import::MJGARDNER::ListProcessing;

# AUTHORITY
# DATE
# DIST
# VERSION

our $LIST = {
  entries => [
               { module => "List::Util" },
               { module => "List::MoreUtils" },
               { module => "List::SomeUtils" },
               { module => "List::UtilsBy" },
               { module => "List::AllUtils" },
               { module => "List::Util::MaybeXS" },
               { module => "List::MoreUtils::XS" },
               { module => "Util::Any" },
               { module => "Scalar::Util" },
               { module => "Hash::Util" },
               { module => "String::Util" },
               { module => "String::CamelCase" },
               { module => "List::Pairwise" },
               { module => "Data::Dumper" },
             ],
  summary => "List of modules mentioned in https://phoenixtrap.com/2021/05/18/a-list-of-perl-list-processing-modules/",
};

1;
# ABSTRACT:

=head1 DESCRIPTION

This L<Acme::CPANModules> module was first automatically generated from list of modules mentioned at L<https://phoenixtrap.com/2021/05/18/a-list-of-perl-list-processing-modules/>.

=cut

