# This file was first automatically generated by gen-acme-cpanmodules-module-from-webpage on Wed May 19 19:08:03 2021 from webpage at https://phoenixtrap.com/2021/04/20/localizing-dates-in-a-perl-web-application/.

package Acme::CPANModules::Import::MJGARDNER::LocalizingDate;

# AUTHORITY
# DATE
# DIST
# VERSION

our $LIST = {
  entries => [
               { module => "DateTime::Locale" },
               { module => "DateTime::Locale::Catalog" },
               { module => "DateTime" },
               { module => "HTTP::AcceptLanguage" },
               { module => "DateTime" },
               { module => "Locale::Maketext" },
             ],
  summary => "List of modules mentioned in https://phoenixtrap.com/2021/04/20/localizing-dates-in-a-perl-web-application/",
};

1;
# ABSTRACT:

=head1 DESCRIPTION

This L<Acme::CPANModules> module was first automatically generated from list of modules mentioned at L<https://phoenixtrap.com/2021/04/20/localizing-dates-in-a-perl-web-application/>.

=cut

