# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:00:32 2018 from module list in Acme::CPANLists::Import::NEILB::LUHN version 0.04.

package Acme::CPANModules::Import::NEILB::LUHN;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/luhn.html]. For the full article, visit the URL.",
  entries     => [
                   { module => "Algorithm::CheckDigits" },
                   { module => "Business::BankCard" },
                   { module => "Business::CardInfo" },
                   { module => "Regexp::Common" },
                   { module => "Regexp::Common::_support" },
                 ],
  summary     => "Checking credit card numbers (LUHN check) (2012)",
};

1;
# ABSTRACT: Checking credit card numbers (LUHN check) (2012)

