# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:00:33 2018 from module list in Acme::CPANLists::Import::NEILB::Markdown version 0.04.

package Acme::CPANModules::Import::NEILB::Markdown;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/markdown.html]. For the full article, visit the URL.",
  entries     => [
                   { module => "Catalyst::Plugin::Markdown" },
                   { module => "DR::SunDown" },
                   { module => "Dist::Zilla::Plugin::ReadmeAnyFromPod" },
                   { module => "Email::Simple" },
                   { module => "Email::Simple::Markdown" },
                   { module => "HTML::WikiConverter" },
                   { module => "HTML::WikiConverter::Markdown" },
                   { module => "Markdent" },
                   { module => "Markdown::Pod" },
                   { module => "Markup::Unified" },
                   { module => "Pod::Markdown" },
                   { module => "Pod::Parser" },
                   { module => "Template" },
                   { module => "Template::Provider::Markdown" },
                   { module => "Text::Markdown" },
                   { module => "Text::Markdown::Discount" },
                   { module => "Text::Markdown::Hoedown" },
                   { module => "Text::Markup" },
                   { module => "Text::Markup::Any" },
                   { module => "Text::MultiMarkdown" },
                 ],
  summary     => "Modules for converting markdown to HTML (2013)",
};

1;
# ABSTRACT: Modules for converting markdown to HTML (2013)

