# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:00:33 2018 from module list in Acme::CPANLists::Import::NEILB::ModulePath version 0.04.

package Acme::CPANModules::Import::NEILB::ModulePath;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/module-path.html]. For the full article, visit the URL.",
  entries     => [
                   { module => "App::moduleswhere" },
                   { module => "App::whichpm" },
                   { module => "Class::Inspector" },
                   { module => "Module::Data" },
                   { module => "Module::Filename" },
                   { module => "Module::Finder" },
                   { module => "Module::Info" },
                   { module => "Module::Locate" },
                   { module => "Module::Mapper" },
                   { module => "Module::Metadata" },
                   { module => "Module::Path" },
                   { module => "Module::Util" },
                   { module => "Path::ScanINC" },
                   { module => "Pod::Perldoc" },
                 ],
  summary     => "Getting a module's path (2012)",
};

1;
# ABSTRACT: Getting a module's path (2012)

