# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:00:33 2018 from module list in Acme::CPANLists::Import::NEILB::Passwords version 0.04.

package Acme::CPANModules::Import::NEILB::Passwords;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/passwords.html]. For the full article, visit the URL.",
  entries     => [
                   { module => "App::Genpass" },
                   { module => "Benchmark" },
                   { module => "Crypt::GeneratePassword" },
                   { module => "Crypt::PW44" },
                   { module => "Crypt::RandPasswd" },
                   { module => "Crypt::XkcdPassword" },
                   { module => "Crypt::YAPassGen" },
                   { module => "Data::Random" },
                   { module => "Data::Random::String" },
                   { module => "Data::SimplePassword" },
                   { module => "Session::Token" },
                   { module => "String::MkPasswd" },
                   { module => "String::Random" },
                   { module => "String::Urandom" },
                   { module => "Text::Password::Pronounceable" },
                 ],
  summary     => "Generating passwords (2012)",
};

1;
# ABSTRACT: Generating passwords (2012)

