# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:00:33 2018 from module list in Acme::CPANLists::Import::NEILB::SpellNumbers version 0.04.

package Acme::CPANModules::Import::NEILB::SpellNumbers;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/spell-numbers.html]. For the full article, visit the URL.",
  entries     => [
                   { module => "Lingua::EN::Inflect" },
                   { module => "Lingua::EN::Numbers" },
                   { module => "Math::BigInt::Named" },
                 ],
  summary     => "Spelling out a number in English (2012)",
};

1;
# ABSTRACT: Spelling out a number in English (2012)

