# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:00:33 2018 from module list in Acme::CPANLists::Import::NEILB::UserAgent version 0.04.

package Acme::CPANModules::Import::NEILB::UserAgent;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://neilb.org/reviews/user-agent.html]. For the full article, visit the URL.",
  entries     => [
                   { module => "HTML::ParseBrowser" },
                   { module => "HTTP::BrowserDetect" },
                   { module => "HTTP::DetectUserAgent" },
                   { module => "HTTP::Headers::UserAgent" },
                   { module => "HTTP::MobileAgent" },
                   { module => "HTTP::MobileAgent::Flash" },
                   { module => "HTTP::UserAgentString::Parser" },
                   { module => "Mobile::UserAgent" },
                   { module => "Parse::HTTP::UserAgent" },
                   { module => "Woothee" },
                 ],
  summary     => "Parsing User-Agent strings (2012)",
};

1;
# ABSTRACT: Parsing User-Agent strings (2012)

